### ISSUE TITLE
Can't import dependency

### ISSUE THREAD

**Issue by vertigod3** [Files-com/files-sdk-java#1]
Hi. Dependency is not searchable in maven central, additionally when trying to import as mentioned in README.md Maven can't find it anywhere.

**Comment by itsChathurangaJ** [comment]
Yes, I got the same issue. Dependency is not there to find

**Comment by bombino** [comment]
Hi folks,

Thanks for letting us know.  We have updated the README to properly reference the right path in Maven Central.  It should work now.
